#!/bin/bash
function echo_red()
{
  tput setaf 1
  echo $1
  tput sgr0
}
function echo_green()
{
  tput setaf 2
  echo $1
  tput sgr0
}
function check()
{
  which $1
  if [ $? != 0 ]; then
    echo_red "Not found"
    return 1
  fi
  echo_green "Found"
  return 0
}

echo_green "Configuration starting"

check "brew" 
if [ $? != 0 ]; then
  `ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"`
fi
check "wget"
if [ $? != 0 ]; then
  `brew install wget`
fi
check "rbenv"
if [ $? != 0 ]; then
  `brew install rbenv ruby-build`
  `rbenv install 2.1.2`
  `rbenv global 2.1.2`
  `rbenv rehash`
fi
check "android"
if [ $? != 0 ]; then
  `brew install android-sdk`
  `brew install android-platform-tools`
fi

${JAVA_HOME?"Need to set JAVA_HOME in bash_profile"}
${ANDROID_HOME?"Need to set ANDROID_HOME bash_profile"}


echo_green "Configuration completed"
